version: "3.9"
services:
  api_test:
    build: .
    ports:
      - ${API_PORT}:8000
    depends_on:
      - database_test
    env_file:
      - .env.test
  black_list_redis_test:
    image: "redis"
    ports:
      - ${BLACKLIST_PORT}:6379
    entrypoint: redis-server --appendonly yes
  database_test:
    image: "mysql:8.0.26"      
    container_name: ${DB_CONTAINER_NAME}    
    env_file:
      - .env.test
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"      
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306    