version: "3.9"
services:
  api_dev:
    build: .
    env_file:
      - .env.dev
    ports:
      - ${API_PORT}:8000
    depends_on:
      - database_dev    
  black_list_redis_dev:
    image: "redis"
    ports:
      - ${BLACKLIST_PORT}:6379    
    entrypoint: redis-server --appendonly yes
  database_dev:
    image: "mysql:8.0.26"
    env_file:
      - .env.dev
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}      
    ports:
      - ${DB_PORT}:3306    