version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - images:/app/images
      - ./public/reviews:/app/public/reviews
  auth-server:
    image: "adairhz/auth-server"
    ports:
      - "50000:50000"
    depends_on:
      - database
    volumes:
      - ./keys:/app/keys
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}      
      DB_CONTAINER_NAME: ${DB_CONTAINER_NAME}
  database:
    image: "mysql:8.0.26"
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}      
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./sql_data:/var/lib/mysql
volumes:
  images: